### ISSUE TITLE
泡网 jcodecraeer是不是已经GG了？

### ISSUE THREAD

**Issue by xiaomeixw** [ditclear/PaoNet#22]
RT
访问不上

**Comment by ditclear** [comment]
应该是，我国庆的时候看看能不能切到wanandroid的API上 ------------------ 原始邮件 ------------------
发件人: "xiong"<notifications@github.com>
发送时间: 2019年9月10日(星期二) 中午1:41
收件人: "ditclear/PaoNet"<PaoNet@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ditclear/PaoNet] 泡网 jcodecraeer是不是已经GG了？ (#22)



RT
 访问不上
 
&mdash;

**Comment by ditclear** [comment]
@xiaomeixw  我今天弄了一下WanAndroid的api，适配了几个功能，readme也更新了，可以看下

**Comment by xiaomeixw** [comment]
@ditclear Thanks，辛苦~~~

**Comment by xiaomeixw** [comment]
泡网恢复了，但是站内很多数据都没有了。现在的数据基本都是之前的备份数据，很多内容已经缺失。泡网经此大劫，后续命运坎坷啊。
